# -*- coding: utf-8 -*-
"""HorseVision AI – Image Classification System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wq6TKgScGEHsUiXHalKfO-gE_prDSspS
"""

import sys
!{sys.executable} -m pip install ml_dtypes>=0.5.0 numpy==1.26.0 --force-reinstall
!{sys.executable} -m pip install keras==3.0.5 --force-reinstall

from google.colab import files

uploaded = files.upload()

import keras

model = keras.models.load_model(
    "keras_model.h5",
    compile=False
)

print("Model loaded successfully")

!pip uninstall -y numpy keras tensorflow jax jaxlib ml_dtypes
!pip install numpy==1.26.4 tensorflow==2.16.1 keras==3.0.5

import tensorflow as tf
import keras

print(tf.__version__)
print(keras.__version__)

from google.colab import files

uploaded = files.upload()

!pip install -U ml_dtypes

!pip install tf_keras

import tf_keras as keras

model = keras.models.load_model(
    "keras_model.h5",
    compile=False
)

print("تم تحميل النموذج بنجاح")

from google.colab import files

uploaded = files.upload()

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

print(labels)

from PIL import Image
import numpy as np

image = Image.open("OSK.jpg").convert("RGB")

image = image.resize((224, 224))

img_array = np.asarray(image).astype(np.float32)

img_array = (img_array / 127.5) - 1

img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

index = np.argmax(prediction)

print("النتيجة:", labels[index])
print("نسبة الثقة:", prediction[0][index])

print(labels)

print(prediction)

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

print(labels)

from google.colab import files

uploaded = files.upload()

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

print(labels)

!rm labels.txt

from google.colab import files
files.upload()

with open("labels.txt") as f:
    labels = [line.strip() for line in f]

print(labels)

index = np.argmax(prediction)

print("النتيجة:", labels[index])
print("نسبة الثقة:", prediction[0][index])

image = Image.open("OSK.jpg").convert("RGB")

image = image.resize((224,224))

image_array = np.asarray(image).astype(np.float32)

# Normalize image values
image_array = (image_array / 127.5) - 1

# Add batch dimension
image_array = np.expand_dims(image_array, axis=0)

print(image_array.shape)

prediction = model.predict(image_array)

print(prediction)

class_index = np.argmax(prediction)

result = labels[class_index]

confidence = prediction[0][class_index]

print("Prediction:", result)
print("Confidence:", confidence)

confidence_percentage = confidence * 100

print(
    "The image is:",
    result,
    "with confidence:",
    round(confidence_percentage, 2),
    "%"
)